import { bam_mat_khau } from './tien_ich_bao_mat.js'

const muoi_mau = 'muoi_du_an_quan_ly_dao_tao_2026'
const mat_khau_mau = bam_mat_khau('Matkhau@123', muoi_mau)

const quyen_quan_tri = [
  'xem_bang_dieu_khien',
  'quan_ly_tai_khoan',
  'cau_hinh_nhap_bang_tinh',
  'xem_lich_hoc',
  'kiem_tra_trung_lich',
  'xem_diem',
  'sua_diem',
  'xuat_du_lieu',
  'tai_tep_khao_thi',
  'nhan_tin',
  'quan_ly_danh_muc',
  'quan_ly_ho_so',
  'quan_ly_phu_luc',
  'phan_quyen_tai_lieu',
  'nhap_lich_van_ban',
]

export function tao_kho_du_lieu() {
  return {
    vai_tro: [
      { ma_vai_tro: 'quan_tri', ten_vai_tro: 'Quan tri he thong', mo_ta: 'Toan quyen cau hinh va kiem soat du lieu' },
      { ma_vai_tro: 'phong_dao_tao', ten_vai_tro: 'Phong dao tao', mo_ta: 'Quan ly hoc vu, lich hoc va ho so dao tao' },
      { ma_vai_tro: 'giao_vien', ten_vai_tro: 'Giao vien', mo_ta: 'Giang day, xem lich duoc phan cong va cap nhat diem' },
      { ma_vai_tro: 'hoc_vien', ten_vai_tro: 'Hoc vien', mo_ta: 'Theo doi lich hoc, diem so va gui hoi dap' },
    ],
    quyen_han: [
      { ma_quyen_han: 'xem_bang_dieu_khien', ten_quyen_han: 'Xem bang dieu khien', duong_dan: '/api/thong-ke-bang-dieu-khien' },
      { ma_quyen_han: 'quan_ly_tai_khoan', ten_quyen_han: 'Quan ly tai khoan', duong_dan: '/api/tai-khoan' },
      { ma_quyen_han: 'cau_hinh_nhap_bang_tinh', ten_quyen_han: 'Cau hinh nhap bang tinh', duong_dan: '/api/nhap-bang-tinh' },
      { ma_quyen_han: 'xem_lich_hoc', ten_quyen_han: 'Xem lich hoc', duong_dan: '/api/lich-hoc' },
      { ma_quyen_han: 'kiem_tra_trung_lich', ten_quyen_han: 'Kiem tra trung lich', duong_dan: '/api/kiem-tra-trung-lich' },
      { ma_quyen_han: 'xem_diem', ten_quyen_han: 'Xem diem', duong_dan: '/api/diem-trung-binh' },
      { ma_quyen_han: 'sua_diem', ten_quyen_han: 'Sua diem lop dang day', duong_dan: '/api/sua-diem' },
      { ma_quyen_han: 'xuat_du_lieu', ten_quyen_han: 'Xuat du lieu', duong_dan: '/api/xuat-danh-sach' },
      { ma_quyen_han: 'tai_tep_khao_thi', ten_quyen_han: 'Tai tep khao thi', duong_dan: '/api/tai-tep-khao-thi' },
      { ma_quyen_han: 'nhan_tin', ten_quyen_han: 'Nhan tin noi bo', duong_dan: '/api/gui-tin-nhan' },
      { ma_quyen_han: 'quan_ly_danh_muc', ten_quyen_han: 'Quan ly danh muc', duong_dan: '/api/danh-muc' },
      { ma_quyen_han: 'quan_ly_ho_so', ten_quyen_han: 'Quan ly ho so', duong_dan: '/api/ho-so' },
      { ma_quyen_han: 'quan_ly_phu_luc', ten_quyen_han: 'Quan ly phu luc', duong_dan: '/api/phu-luc-hoi-dong' },
      { ma_quyen_han: 'phan_quyen_tai_lieu', ten_quyen_han: 'Phan quyen tai lieu', duong_dan: '/api/phan-quyen-tai-lieu' },
      { ma_quyen_han: 'nhap_lich_van_ban', ten_quyen_han: 'Nhap lich tu van ban', duong_dan: '/api/nhap-lich-van-ban' },
    ],
    vai_tro_quyen_han: [
      ...quyen_quan_tri.map((ma_quyen_han) => ({ ma_vai_tro: 'quan_tri', ma_quyen_han })),
      ...quyen_quan_tri.filter((ma_quyen_han) => ma_quyen_han !== 'sua_diem').map((ma_quyen_han) => ({ ma_vai_tro: 'phong_dao_tao', ma_quyen_han })),
      ...['xem_bang_dieu_khien', 'xem_lich_hoc', 'kiem_tra_trung_lich', 'xem_diem', 'sua_diem', 'xuat_du_lieu', 'nhan_tin', 'quan_ly_phu_luc'].map((ma_quyen_han) => ({ ma_vai_tro: 'giao_vien', ma_quyen_han })),
      ...['xem_bang_dieu_khien', 'xem_lich_hoc', 'xem_diem', 'nhan_tin'].map((ma_quyen_han) => ({ ma_vai_tro: 'hoc_vien', ma_quyen_han })),
    ],
    nguoi_dung: [
      {
        ma_nguoi_dung: 'nd_quan_tri_01',
        ho_va_ten: 'Nguyen Van Hung',
        thu_dien_tu: 'hung@dao-tao.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'quan_tri',
        ma_dang_nhap_ngoai: 'ngoai_hung_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
      {
        ma_nguoi_dung: 'nd_dao_tao_01',
        ho_va_ten: 'Pham Thi Thanh',
        thu_dien_tu: 'thanh@dao-tao.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'phong_dao_tao',
        ma_dang_nhap_ngoai: 'ngoai_thanh_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
      {
        ma_nguoi_dung: 'nd_giao_vien_01',
        ho_va_ten: 'Tran Minh Khoa',
        thu_dien_tu: 'khoa@dao-tao.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'giao_vien',
        ma_dang_nhap_ngoai: 'ngoai_khoa_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
      {
        ma_nguoi_dung: 'nd_giao_vien_02',
        ho_va_ten: 'Le Thu Ha',
        thu_dien_tu: 'ha@dao-tao.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'giao_vien',
        ma_dang_nhap_ngoai: 'ngoai_ha_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
      {
        ma_nguoi_dung: 'nd_hoc_vien_01',
        ho_va_ten: 'Le Minh Manh',
        thu_dien_tu: 'manh@hoc-vien.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'hoc_vien',
        ma_dang_nhap_ngoai: 'ngoai_manh_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
      {
        ma_nguoi_dung: 'nd_hoc_vien_02',
        ho_va_ten: 'Tran Thu Trang',
        thu_dien_tu: 'trang@hoc-vien.vn',
        muoi_mat_khau: muoi_mau,
        mat_khau_da_bam: mat_khau_mau,
        ma_vai_tro: 'hoc_vien',
        ma_dang_nhap_ngoai: 'ngoai_trang_01',
        da_xoa: false,
        thoi_diem_xoa: null,
      },
    ],
    phong_ban: [
      { ma_phong_ban: 'phong_dao_tao', ten_phong_ban: 'Phong dao tao', mo_ta: 'Dieu phoi ke hoach hoc vu', da_xoa: false },
      { ma_phong_ban: 'phong_khao_thi', ten_phong_ban: 'Phong khao thi', mo_ta: 'Quan ly de thi va ket qua khao thi', da_xoa: false },
    ],
    khoa_ban: [
      { ma_khoa_ban: 'khoa_cong_nghe', ten_khoa_ban: 'Khoa cong nghe', ma_phong_ban: 'phong_dao_tao', da_xoa: false },
      { ma_khoa_ban: 'khoa_du_lieu', ten_khoa_ban: 'Khoa du lieu', ma_phong_ban: 'phong_dao_tao', da_xoa: false },
    ],
    doi_tuong_dao_tao: [
      { ma_doi_tuong_dao_tao: 'he_dai_hoc', ten_doi_tuong_dao_tao: 'Dai hoc', bac_dao_tao: 'Cu nhan', da_xoa: false },
      { ma_doi_tuong_dao_tao: 'he_cao_dang', ten_doi_tuong_dao_tao: 'Cao dang', bac_dao_tao: 'Thuc hanh', da_xoa: false },
      { ma_doi_tuong_dao_tao: 'he_thac_si', ten_doi_tuong_dao_tao: 'Thac si', bac_dao_tao: 'Sau dai hoc', da_xoa: false },
    ],
    khoa_hoc: [
      { ma_khoa_hoc: 'khoa_2024', ten_khoa_hoc: 'Khoa tuyen sinh nam 2024', nam_bat_dau: 2024, nam_ket_thuc: 2028 },
      { ma_khoa_hoc: 'khoa_2025', ten_khoa_hoc: 'Khoa tuyen sinh nam 2025', nam_bat_dau: 2025, nam_ket_thuc: 2029 },
    ],
    nganh_hoc: [
      { ma_nganh_hoc: 'nganh_ky_thuat_phan_mem', ten_nganh_hoc: 'Ky thuat phan mem', ma_khoa_hoc: 'khoa_2024', ma_doi_tuong_dao_tao: 'he_dai_hoc', ma_khoa_ban: 'khoa_cong_nghe', tieu_chuan: 'Dat chuan dau ra cong nghe phan mem' },
      { ma_nganh_hoc: 'nganh_khoa_hoc_du_lieu', ten_nganh_hoc: 'Khoa hoc du lieu', ma_khoa_hoc: 'khoa_2024', ma_doi_tuong_dao_tao: 'he_dai_hoc', ma_khoa_ban: 'khoa_du_lieu', tieu_chuan: 'Dat chuan phan tich du lieu' },
    ],
    mon_hoc: [
      { ma_mon_hoc: 'mon_lap_trinh_co_so', ten_mon_hoc: 'Lap trinh co so', so_tin_chi: 3, so_buoi_hoc: 12, loai_mon_hoc: 'Thuc hanh', ma_nganh_hoc: 'nganh_ky_thuat_phan_mem' },
      { ma_mon_hoc: 'mon_co_so_du_lieu', ten_mon_hoc: 'Co so du lieu', so_tin_chi: 3, so_buoi_hoc: 10, loai_mon_hoc: 'Ly thuyet', ma_nganh_hoc: 'nganh_khoa_hoc_du_lieu' },
      { ma_mon_hoc: 'mon_giai_thuat', ten_mon_hoc: 'Giai thuat nang cao', so_tin_chi: 4, so_buoi_hoc: 14, loai_mon_hoc: 'Ket hop', ma_nganh_hoc: 'nganh_ky_thuat_phan_mem' },
    ],
    phong_hoc: [
      { ma_phong_hoc: 'phong_a201', ten_phong_hoc: 'Phong thuc hanh A201', suc_chua: 36, loai_phong: 'Thuc hanh', trang_thai: 'san_sang' },
      { ma_phong_hoc: 'phong_b305', ten_phong_hoc: 'Phong ly thuyet B305', suc_chua: 70, loai_phong: 'Ly thuyet', trang_thai: 'san_sang' },
      { ma_phong_hoc: 'phong_truc_tuyen', ten_phong_hoc: 'Phong truc tuyen', suc_chua: 120, loai_phong: 'Truc tuyen', trang_thai: 'san_sang' },
    ],
    lop_hoc: [
      { ma_lop_hoc: 'lop_pm_01', ten_lop_hoc: 'PM01 - Lap trinh co so', ma_mon_hoc: 'mon_lap_trinh_co_so', ma_nganh_hoc: 'nganh_ky_thuat_phan_mem', ma_giao_vien: 'nd_giao_vien_01', trang_thai: 'dang_mo', da_xoa: false },
      { ma_lop_hoc: 'lop_dl_01', ten_lop_hoc: 'DL01 - Co so du lieu', ma_mon_hoc: 'mon_co_so_du_lieu', ma_nganh_hoc: 'nganh_khoa_hoc_du_lieu', ma_giao_vien: 'nd_giao_vien_02', trang_thai: 'dang_mo', da_xoa: false },
      { ma_lop_hoc: 'lop_gt_01', ten_lop_hoc: 'GT01 - Giai thuat nang cao', ma_mon_hoc: 'mon_giai_thuat', ma_nganh_hoc: 'nganh_ky_thuat_phan_mem', ma_giao_vien: 'nd_giao_vien_01', trang_thai: 'dang_mo', da_xoa: false },
    ],
    hoc_vien_lop_hoc: [
      { ma_lop_hoc: 'lop_pm_01', ma_hoc_vien: 'nd_hoc_vien_01' },
      { ma_lop_hoc: 'lop_pm_01', ma_hoc_vien: 'nd_hoc_vien_02' },
      { ma_lop_hoc: 'lop_dl_01', ma_hoc_vien: 'nd_hoc_vien_01' },
    ],
    ho_so_hoc_vien: [
      { ma_hoc_vien: 'nd_hoc_vien_01', so_can_cuoc: '079200000001', ngay_sinh: '2002-03-12', que_quan: 'Ha Noi', don_vi: 'Dai doi 1', trang_thai_hoc_tap: 'dang_hoc', ma_tep_anh_can_cuoc: null, da_xoa: false },
      { ma_hoc_vien: 'nd_hoc_vien_02', so_can_cuoc: '079200000002', ngay_sinh: '2002-09-22', que_quan: 'Da Nang', don_vi: 'Dai doi 2', trang_thai_hoc_tap: 'dang_hoc', ma_tep_anh_can_cuoc: null, da_xoa: false },
    ],
    ho_so_giao_vien: [
      { ma_giao_vien: 'nd_giao_vien_01', cap_bac: 'Thuong uy', hoc_vi: 'Thac si', chuc_vu: 'Giang vien', ma_khoa_ban: 'khoa_cong_nghe', ma_tep_anh_the: null, ma_tep_anh_can_cuoc: null, so_buoi_day: 28, da_xoa: false },
      { ma_giao_vien: 'nd_giao_vien_02', cap_bac: 'Dai uy', hoc_vi: 'Tien si', chuc_vu: 'Giang vien chinh', ma_khoa_ban: 'khoa_du_lieu', ma_tep_anh_the: null, ma_tep_anh_can_cuoc: null, so_buoi_day: 24, da_xoa: false },
    ],
    tiet_hoc: [
      { ma_tiet_hoc: 'tiet_01', ten_tiet_hoc: 'Tiet 1', thoi_gian_bat_dau: '08:00', thoi_gian_ket_thuc: '09:30' },
      { ma_tiet_hoc: 'tiet_02', ten_tiet_hoc: 'Tiet 2', thoi_gian_bat_dau: '10:00', thoi_gian_ket_thuc: '11:30' },
      { ma_tiet_hoc: 'tiet_03', ten_tiet_hoc: 'Tiet 3', thoi_gian_bat_dau: '13:00', thoi_gian_ket_thuc: '14:30' },
    ],
    lich_hoc: [
      { ma_lich_hoc: 'lich_001', ma_lop_hoc: 'lop_pm_01', ma_mon_hoc: 'mon_lap_trinh_co_so', ma_giao_vien: 'nd_giao_vien_01', ma_phong_hoc: 'phong_a201', ma_tiet_hoc: 'tiet_02', ngay_hoc: '2026-06-01' },
      { ma_lich_hoc: 'lich_002', ma_lop_hoc: 'lop_gt_01', ma_mon_hoc: 'mon_giai_thuat', ma_giao_vien: 'nd_giao_vien_01', ma_phong_hoc: 'phong_b305', ma_tiet_hoc: 'tiet_02', ngay_hoc: '2026-06-01' },
      { ma_lich_hoc: 'lich_003', ma_lop_hoc: 'lop_dl_01', ma_mon_hoc: 'mon_co_so_du_lieu', ma_giao_vien: 'nd_giao_vien_02', ma_phong_hoc: 'phong_a201', ma_tiet_hoc: 'tiet_02', ngay_hoc: '2026-06-01' },
      { ma_lich_hoc: 'lich_004', ma_lop_hoc: 'lop_dl_01', ma_mon_hoc: 'mon_co_so_du_lieu', ma_giao_vien: 'nd_giao_vien_02', ma_phong_hoc: 'phong_truc_tuyen', ma_tiet_hoc: 'tiet_03', ngay_hoc: '2026-06-02' },
    ],
    cau_hinh_cong_thuc_diem: [
      {
        ma_cong_thuc: 'cong_thuc_mac_dinh',
        ma_mon_hoc: 'tat_ca',
        ten_cong_thuc: 'Cong thuc diem chuan',
        thanh_phan: [
          { truong_diem: 'diem_thuc_hanh_1', trong_so: 0.08 },
          { truong_diem: 'diem_thuc_hanh_2', trong_so: 0.08 },
          { truong_diem: 'diem_thuc_hanh_3', trong_so: 0.08 },
          { truong_diem: 'diem_thuc_hanh_4', trong_so: 0.08 },
          { truong_diem: 'diem_bai_tap_1', trong_so: 0.15 },
          { truong_diem: 'diem_bai_tap_2', trong_so: 0.15 },
          { truong_diem: 'diem_thi_cuoi_ky', trong_so: 0.38 },
        ],
      },
    ],
    mau_bang_diem: [
      { ma_mau_bang_diem: 'mau_mac_dinh', ten_mau_bang_diem: 'Mau diem chuan', pham_vi_ap_dung: 'tat_ca', cong_thuc: 'tong_diem_theo_trong_so', thoi_diem_tao: '2026-05-26T00:00:00.000Z' },
    ],
    diem_thanh_phan: [
      {
        ma_diem: 'diem_001',
        ma_hoc_vien: 'nd_hoc_vien_01',
        ma_lop_hoc: 'lop_pm_01',
        ma_mon_hoc: 'mon_lap_trinh_co_so',
        diem_thuc_hanh_1: 8.5,
        diem_thuc_hanh_2: 9,
        diem_thuc_hanh_3: 7.5,
        diem_thuc_hanh_4: 8,
        diem_bai_tap_1: 8.8,
        diem_bai_tap_2: 9.1,
        diem_thi_cuoi_ky: 8.4,
      },
      {
        ma_diem: 'diem_002',
        ma_hoc_vien: 'nd_hoc_vien_02',
        ma_lop_hoc: 'lop_pm_01',
        ma_mon_hoc: 'mon_lap_trinh_co_so',
        diem_thuc_hanh_1: 4.5,
        diem_thuc_hanh_2: 5,
        diem_thuc_hanh_3: 5.4,
        diem_thuc_hanh_4: 4.9,
        diem_bai_tap_1: 5.2,
        diem_bai_tap_2: 5.6,
        diem_thi_cuoi_ky: 4.2,
      },
      {
        ma_diem: 'diem_003',
        ma_hoc_vien: 'nd_hoc_vien_01',
        ma_lop_hoc: 'lop_dl_01',
        ma_mon_hoc: 'mon_co_so_du_lieu',
        diem_thuc_hanh_1: 9.1,
        diem_thuc_hanh_2: 8.8,
        diem_thuc_hanh_3: 9.4,
        diem_thuc_hanh_4: 9,
        diem_bai_tap_1: 8.7,
        diem_bai_tap_2: 9.2,
        diem_thi_cuoi_ky: 9.3,
      },
    ],
    lich_su_diem: [],
    bo_nho_dem_phieu_diem: [],
    cau_hinh_nhap_bang_tinh: [
      { ma_cau_hinh_nhap: 'nhap_danh_sach_hoc_vien', ten_cau_hinh: 'Danh sach hoc vien', mau_ten_trang: 'danh_sach_*', che_do_khop: 'dai_dien' },
      { ma_cau_hinh_nhap: 'nhap_bang_diem', ten_cau_hinh: 'Bang diem thanh phan', mau_ten_trang: 'diem_*', che_do_khop: 'dai_dien' },
    ],
    cau_hinh_nhap_bang_tinh_cot: [
      { ma_cau_hinh_nhap: 'nhap_danh_sach_hoc_vien', truong_he_thong: 'ho_va_ten', ten_tieu_de: 'Ho ten sinh vien', cot_bang_tinh: 'B', bat_buoc: true },
      { ma_cau_hinh_nhap: 'nhap_danh_sach_hoc_vien', truong_he_thong: 'thu_dien_tu', ten_tieu_de: 'Thu dien tu', cot_bang_tinh: 'C', bat_buoc: false },
      { ma_cau_hinh_nhap: 'nhap_bang_diem', truong_he_thong: 'ma_hoc_vien', ten_tieu_de: 'Ma sinh vien', cot_bang_tinh: 'A', bat_buoc: true },
      { ma_cau_hinh_nhap: 'nhap_bang_diem', truong_he_thong: 'diem_thuc_hanh_1', ten_tieu_de: 'Diem thuc hanh 1', cot_bang_tinh: 'C', bat_buoc: true },
      { ma_cau_hinh_nhap: 'nhap_bang_diem', truong_he_thong: 'diem_thi_cuoi_ky', ten_tieu_de: 'Diem cuoi ky', cot_bang_tinh: 'F', bat_buoc: true },
    ],
    tep_tin: [
      { ma_tep_tin: 'tep_001', ten_tep: 'de_cuong_lap_trinh_co_so.pdf', loai_tep: 'tep_khao_thi', dung_luong_byte: 2457600, ma_nguoi_tai: 'nd_dao_tao_01', duong_dan_noi_bo: '/tep/de_cuong_lap_trinh_co_so.pdf' },
    ],
    quyen_xem_tai_lieu: [
      { ma_tep_tin: 'tep_001', ma_vai_tro: 'quan_tri' },
      { ma_tep_tin: 'tep_001', ma_vai_tro: 'phong_dao_tao' },
      { ma_tep_tin: 'tep_001', ma_vai_tro: 'giao_vien' },
    ],
    tai_lieu_giang_day: [
      { ma_tai_lieu_giang_day: 'tlgd_001', ma_giao_vien: 'nd_giao_vien_01', ma_mon_hoc: 'mon_lap_trinh_co_so', ma_tep_tin: 'tep_001', ten_tai_lieu: 'De cuong lap trinh co so', da_xoa: false },
    ],
    tep_phu_luc_hoi_dong: [
      { ma_tep_phu_luc: 'pl_001', loai_phu_luc: 'phu_luc_hoi_dong_1', ma_lop_hoc: 'lop_pm_01', ten_tep: 'phu_luc_hoi_dong_1_lop_pm_01.doc', dung_luong_byte: 1024, dang_bat: true, da_xoa: false },
    ],
    ket_qua_quet_the: [],
    cuoc_hoi_thoai: [
      { ma_cuoc_hoi_thoai: 'hoi_thoai_001', tieu_de: 'Hoi dap lich thi', ma_hoc_vien: 'nd_hoc_vien_01', ma_phong_dao_tao: 'nd_dao_tao_01' },
    ],
    tin_nhan: [
      { ma_tin_nhan: 'tin_001', ma_cuoc_hoi_thoai: 'hoi_thoai_001', ma_nguoi_gui: 'nd_hoc_vien_01', noi_dung: 'Em muon xac nhan lich thi cuoi ky.', thoi_diem_gui: '2026-05-26T09:00:00.000Z' },
      { ma_tin_nhan: 'tin_002', ma_cuoc_hoi_thoai: 'hoi_thoai_001', ma_nguoi_gui: 'nd_dao_tao_01', noi_dung: 'Phong dao tao da ghi nhan va se phan hoi trong ngay.', thoi_diem_gui: '2026-05-26T09:05:00.000Z' },
    ],
    phien_dang_nhap: [],
  }
}
